In [1]:
import os
import serial
import numpy as np
import time
import heapq

In [2]:
class wrist():
    def __init__(self,name,length):
        self.name = name
        self.data_path = os.getcwd() + "/data/" + name +".txt"
        self.length = length
        self.data = []
        self.ser = serial.Serial('/dev/ttyACM0',9600)
        self.gesture = ""
    
    def get_data(self):
        if(not os.path.exists(self.data_path)):
            print("file not exists")
            return False
        data = open(self.data_path,"r", encoding='utf-8') 
        self.data_to_numpy(data)
        data.close()
        return True
    
    def data_to_numpy(self,data):
        while True:
            line = data.readline()
            if not line: break
            temp = []
            line_data = line[:-1].split(" ")
            print(line_data)
            temp.append(line_data[0])
            temp.append(np.array(list(map(float, line_data[1:]))))
            self.data.append(temp)
        return
    
    def save_data(self):
        file = open(self.data_path, "w")
        tempstr = ""
        for temp in self.data:
            tempstr += temp[0]
            for i in temp[1].tolist():
                tempstr += " "
                tempstr += str(i)
            tempstr += "\n"
        file.write(tempstr)
        file.close()
    
    def add_gesture(self,gesture_name):
        maxcount = 50
        temp = []
        temp.append(gesture_name)
        count = 0
        tempdata = np.array([0,0,0,0])
        while(count < maxcount):
            res = self.ser.readline()
            print(res.decode()[:len(res)])
            print(np.array(res.decode()[:len(res)]))
            
            tempdata += np.array(list(map(int, res.decode()[:len(res)].split(" "))))
            count += 1
        
        temp.append(tempdata/maxcount)
        self.data.append(temp)
        return
    
    def calculate_gesture(self,current):
        temp_heap = []
        heapq.heapify(temp_heap)
        for i in self.data:
            print("here")
            diff = i[1] - current
            dis_sq = 0
            for j in diff.tolist():
                dis_sq += j * j
            heapq.heappush(temp_heap, (dis_sq, i[0]))
        return heapq.heappop(temp_heap)[1]
    
    def listen(self):
        while True:
            res = self.ser.readline()
            print(res.decode()[:len(res)].split(" "))
            current = np.array(list(map(float, res.decode()[:len(res)].split(" "))))
            print(current)
            self.gesture = self.calculate_gesture(current)
            print(self.gesture)
            
    def listen_data(self):
        while True:
            res = self.ser.readline()
            print(np.array(list(map(float, res.decode()[:len(res)].split(" ")))))
#             print(type(res.decode()[:len(res)]))
        

In [3]:
wr1 = wrist("rpf511",4)
wr1.get_data()

['loosen', '0.0', '0.0', '0.0', '0.0']


True

In [114]:
# wr1.add_gesture("loosen")
wr1.add_gesture("paper")

In [4]:
print(wr1.data)

[['loosen', array([0., 0., 0., 0.])]]


In [116]:
# wr1.save_data()

In [ ]:
wr1.listen_data()

[570.   7. 629.   0.]
[597.  87. 635.   0.]
[638. 464. 632.   0.]
[627. 229. 649.   0.]
[577.   0. 649.   0.]
[240.   0. 514.   0.]
[  0.   0. 224.   0.]
[  0.   0. 227.   0.]
[  0.   0. 240.   0.]
[  0.   0. 244.   0.]
[  0.   0. 228.   0.]
[  0.   0. 324.   0.]
[332.   0. 555.   0.]
[315.   0. 578.   0.]
[287.   0. 605.   0.]
[311.   0. 611.   0.]
[291.   0. 610.   0.]
[279.   0. 616.   0.]
[284.   0. 616.   0.]
[263.   0. 605.   0.]
[275.   0. 611.   0.]
[256.   0. 599.   0.]
[226.   0. 582.   0.]
[252.   0. 596.   0.]
[199.   0. 522.   0.]
[  0.   0. 354.   0.]
[  0.   0. 457.   0.]
[  0.   0. 373.   0.]
[  0.   0. 339.   0.]
[  0.   0. 322.   0.]
[  0.   0. 290.   0.]
[  0.   0. 294.   0.]
[  0.   0. 271.   0.]
[  0.   0. 244.   0.]
[  0.   0. 230.   0.]
[  0.   0. 220.   0.]
[  0.   0. 234.   0.]
[  0.   0. 237.   0.]
[  0.   0. 202.   0.]
[  0.   0. 366.   0.]
[  0.   0. 306.   0.]
[  0.   0. 232.   0.]
[  0.   0. 171.   0.]
[ 19.   0. 251.  19.]
[108.   0. 295.  26.]
[  0.   0.

In [7]:
wr1.listen()

['0', '0', '0', '0\n']
[0. 0. 0. 0.]
here
loosen
['0', '0', '0', '0\n']
[0. 0. 0. 0.]
here
loosen
['0', '0', '0', '0\n']
[0. 0. 0. 0.]
here
loosen
['0', '8', '0', '0\n']
[0. 8. 0. 0.]
here
loosen
['0', '0', '0', '0\n']
[0. 0. 0. 0.]
here
loosen
['0', '186', '0', '0\n']
[  0. 186.   0.   0.]
here
loosen
['0', '0', '0', '0\n']
[0. 0. 0. 0.]
here
loosen
['92', '0', '0', '0\n']
[92.  0.  0.  0.]
here
loosen
['0', '0', '0', '0\n']
[0. 0. 0. 0.]
here
loosen
['0', '0', '0', '0\n']
[0. 0. 0. 0.]
here
loosen
['0', '0', '0', '8\n']
[0. 0. 0. 8.]
here
loosen
['0', '0', '0', '71\n']
[ 0.  0.  0. 71.]
here
loosen
['0', '0', '0', '68\n']
[ 0.  0.  0. 68.]
here
loosen
['0', '0', '0', '0\n']
[0. 0. 0. 0.]
here
loosen
['0', '0', '0', '0\n']
[0. 0. 0. 0.]
here
loosen
['0', '0', '0', '0\n']
[0. 0. 0. 0.]
here
loosen
['0', '0', '0', '0\n']
[0. 0. 0. 0.]
here
loosen
['0', '0', '0', '0\n']
[0. 0. 0. 0.]
here
loosen
['0', '0', '179', '0\n']
[  0.   0. 179.   0.]
here
loosen
['0', '0', '0', '0\n']
[0. 0. 0. 0

KeyboardInterrupt: 

In [90]:


ser = serial.Serial('/dev/ttyACM0',9600)
time.sleep(2)

id = 1
id = str(id)

print(id)

while True:
	res = ser.readline()
	print(res.decode()[:len(res)])

1
0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0

0 0 0 0



KeyboardInterrupt: 