In [1]:
import os
import serial
import numpy as np
import time
import heapq
import pyautogui

In [81]:
class wrist():
    def __init__(self,name,length):
        self.name = name
        #rpf511
        #self.data_path = os.getcwd() + "/data/" + name +".txt" 
        #LightYe4r
        self.data_path = "C:\\piledata\\class_data\\3학년\창의캡스톤디자인\\wrist_data_gathering\\data\\"+ name + ".txt"
        self.length = length
        self.data = []
        #rpf511
        #self.ser = serial.Serial('/dev/ttyACM0',9600) rpf511
        #LightYe4r
        self.ser = serial.Serial('COM3',9600)
        self.gesture = ""
        self.key = ""
    
    def get_data(self):
        if(not os.path.exists(self.data_path)):
            print("file not exists")
            return False
        data = open(self.data_path,"r", encoding='utf-8') 
        self.data_to_numpy(data)
        data.close()
        return True
    
    def data_to_numpy(self,data):
        while True:
            line = data.readline()
            if not line: break
            temp = []
            line_data = line[:-1].split(" ")
            print(line_data)
            temp.append(line_data[0])
            temp.append(np.array(list(map(float, line_data[1:]))))
            self.data.append(temp)
        return
    
    def save_data(self):
        file = open(self.data_path, "w")
        tempstr = ""
        for temp in self.data:
            tempstr += temp[0]
            for i in temp[1].tolist():
                tempstr += " "
                tempstr += str(i)
            tempstr += "\n"
        file.write(tempstr)
        file.close()
    
    def add_gesture(self,gesture_name):
        self.key = input("Which input would you like to use?")
        maxcount = 50
        temp = []
        temp.append(gesture_name)
        count = 0
        tempdata = np.array([0,0,0,0])
        while(count < maxcount):
            res = self.ser.readline()
            print(res.decode()[:len(res)])
            print(np.array(res.decode()[:len(res)]))
            
            tempdata += np.array(list(map(int, res.decode()[:len(res)].split(" "))))
            count += 1
        
        temp.append(tempdata/maxcount)
        self.data.append(temp)
        return

    
    def calculate_gesture(self,current):
        temp_heap = []
        heapq.heapify(temp_heap)
        for i in self.data:
#             print(i)
            diff = i[1] - current
            dis_sq = 0
            for j in diff.tolist():
                dis_sq += j * j
            heapq.heappush(temp_heap, (dis_sq, i[0]))
        return heapq.heappop(temp_heap)[1]
    
           
    def listen_data(self):
        while True:
            res = self.ser.readline()
            print(np.array(list(map(float, res.decode()[:len(res)].split(" ")))))
#             print(type(res.decode()[:len(res)]))

    def listen(self):
        while True:
            res = self.ser.readline()
            current = np.array(list(map(float, res.decode()[:len(res)].split(" "))))
            self.gesture = self.calculate_gesture(current)
            print(self.gesture)
            print(self.key)
            pyautogui.press(self.key)
            

In [82]:
#rpf511
#wr1 = wrist("rpf511", 4)
#LightYe4r
wr1 = wrist("LightYe4r",4)
wr1.get_data()

file not exists


False

In [ ]:
print(pyautogui.KEYBOARD_KEYS) #check possible input

In [86]:
#wr1.add_gesture("loosen")
#wr1.add_gesture("paper")
#wr1.add_gesture("reg_scissor")
wr1.add_gesture("fake_scissor")

0 730 688 756

0 730 688 756

0 734 692 756

0 734 692 756

0 742 697 758

0 742 697 758

0 747 703 757

0 747 703 757

0 745 686 753

0 745 686 753

3 751 700 756

3 751 700 756

0 749 681 753

0 749 681 753

0 747 696 753

0 747 696 753

0 752 693 750

0 752 693 750

0 751 672 749

0 751 672 749

0 753 684 750

0 753 684 750

0 750 651 740

0 750 651 740

0 752 659 738

0 752 659 738

0 738 520 725

0 738 520 725

0 199 0 0

0 199 0 0

0 272 0 0

0 272 0 0

1 302 0 2

1 302 0 2

0 209 0 0

0 209 0 0

0 474 0 0

0 474 0 0

0 491 0 0

0 491 0 0

0 437 0 0

0 437 0 0

0 468 0 33

0 468 0 33

0 481 0 2

0 481 0 2

0 477 0 0

0 477 0 0

0 490 0 0

0 490 0 0

0 491 0 0

0 491 0 0

0 485 1 0

0 485 1 0

0 468 0 0

0 468 0 0

0 478 0 0

0 478 0 0

0 460 0 0

0 460 0 0

2 454 0 0

2 454 0 0

0 452 0 0

0 452 0 0

0 427 0 0

0 427 0 0

0 395 0 51

0 395 0 51

0 422 0 123

0 422 0 123

0 433 0 122

0 433 0 122

0 401 0 106

0 401 0 106

0 388 0 118

0 388 0 118

0 390 0 99

0 390 0 99

0 376 4 

In [87]:
print(wr1.data)

[['loosen', array([ 0.18, 37.72,  0.26,  0.14])], ['paper', array([581.58, 636.3 , 602.92, 668.08])], ['reg_scissor', array([219.58, 710.6 , 641.32, 700.8 ])], ['fake_scissor', array([1.2000e-01, 4.9232e+02, 1.8858e+02, 2.3008e+02])]]


In [88]:
wr1.save_data()

In [69]:
wr1.listen_data()

[254. 250. 239. 231.]
[174. 169. 163. 170.]
[177. 177. 175. 180.]
[225. 227. 235. 241.]
[331. 348. 373. 379.]
[489. 504. 520. 539.]
[658. 663. 679. 689.]
[759. 769. 781. 782.]
[831. 816. 828. 831.]
[825. 827. 826. 820.]
[777. 771. 761. 750.]
[666. 643. 630. 611.]
[500. 490. 470. 453.]
[355. 342. 328. 312.]
[248. 240. 226. 223.]
[170. 159. 158. 164.]
[166. 160. 164. 173.]
[220. 223. 227. 238.]
[328. 340. 359. 377.]
[479. 496. 509. 520.]
[624. 642. 649. 666.]
[737. 748. 745. 761.]
[809. 814. 821. 802.]
[813. 820. 825. 815.]
[778. 766. 764. 756.]
[659. 643. 636. 612.]
[506. 491. 473. 453.]
[351. 338. 325. 310.]
[233. 224. 216. 208.]
[154. 153. 168. 153.]
[170. 171. 172. 168.]
[218. 222. 231. 241.]


KeyboardInterrupt: 

In [ ]:
wr1.listen()

loosen
loosen
loosen
loosen
loosen
loosen
loosen
fake_scissor
fake_scissor
loosen
fake_scissor
fake_scissor
fake_scissor
fake_scissor
fake_scissor
fake_scissor
fake_scissor
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
paper
paper
paper
paper
paper
reg_scissor
reg_scissor
reg_scissor
reg_scissor
reg_scissor
reg_scissor
fake_scissor
fake_scissor
fake_scissor
fake_scissor
fake_scissor
fake_scissor
reg_scissor
paper
paper
paper
paper
paper
paper
paper
paper
paper
paper
paper
paper
paper
paper
paper
paper
paper
paper
paper
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loosen
loo